DECLARE @SERVICIO VARCHAR(20)='Urgencia', @CODPLANTILLAENCUESTA INT =1

SELECT ROW_NUMBER()OVER(ORDER BY ORDEN, CAMPO)CNS, Z. *,  
CASE WHEN TIPO  IN ('RadioButton','Lista','Alfanumerico') then REPLACE(REPLACE(REPLACE('rbt'+ 'JAGR' +CASE WHEN COALESCE(SERVICIO,'')='' THEN 'Blanco' ELSE COALESCE(SERVICIO,'') END + 'JAGR' + PREGUNTA  + 'JAGR' + VALOR +'JAGR' +CONVERT(VARCHAR(MAX), CAMPO) + CONVERT(VARCHAR(MAX), ROW_NUMBER()OVER(ORDER BY ORDEN, CAMPO))
,' ','1sp4c10'),',','C0m4'),'?','Pr3gunt4')
ELSE '' END IDCAMPO

 FROM(
SELECT  MIN(ORDEN) ORDEN,SERVICIO,PREGUNTA, PREGUNTA  VALOR, 'Pregunta' TIPOREGISTRO,'Titulo' TIPO, 0 CAMPO
FROM PLANTILLAENCUESTAD 
WHERE SERVICIO=COALESCE(@SERVICIO,'')   and CODPLANTILLAENCUESTA=@CODPLANTILLAENCUESTA
AND COALESCE(PREGUNTA,'')<>''
GROUP BY PREGUNTA,SERVICIO
UNION ALL
SELECT  MIN(ORDEN) ORDEN,SERVICIO,PREGUNTA, PREGUNTA  VALOR, 'Pregunta' TIPOREGISTRO,'Titulo' TIPO, 0 CAMPO
FROM PLANTILLAENCUESTAD 
WHERE SERVICIO='' AND EVALUADO<>''   and CODPLANTILLAENCUESTA=@CODPLANTILLAENCUESTA 
AND COALESCE(PREGUNTA,'')<>''
GROUP BY PREGUNTA,SERVICIO
UNION ALL
SELECT  ORDEN,SERVICIO,PREGUNTA, EVALUADO , 'Evaluado', TIPO, CAMPO
FROM PLANTILLAENCUESTAD WHERE SERVICIO=@SERVICIO and CODPLANTILLAENCUESTA=@CODPLANTILLAENCUESTA
--GROUP BY EVALUADO,PREGUNTA, SERVICIO
UNION ALL 

SELECT ORDEN,SERVICIO,PREGUNTA,'' , 'EvaluadoSerBlanco', TIPO, CAMPO
FROM PLANTILLAENCUESTAD 

WHERE coalesce(SERVICIO,'')='' AND COALESCE(EVALUADO,'')='' and CODPLANTILLAENCUESTA=@CODPLANTILLAENCUESTA
UNION ALL
SELECT ORDEN,SERVICIO,PREGUNTA, EVALUADO, 'EvaluadoNoBlanco', TIPO, CAMPO
FROM PLANTILLAENCUESTAD 

WHERE SERVICIO='' AND COALESCE(EVALUADO,'')<>'' and CODPLANTILLAENCUESTA=@CODPLANTILLAENCUESTA
) Z

ORDER BY ORDEN, CAMPO