CREATE TABLE PLANTILLAENCUESTA
 (
CODPLANTILLAENCUESTA INT IDENTITY (1,1)  NOT NULL,
DESCRIPCION VARCHAR(300)
)


create  TABLE PLANTILLAENCUESTAD
 (
CODPLANTILLAENCUESTA INT NOT NULL,
CAMPO INT IDENTITY (1,1),
ORDEN INT NOT NULL,
SERVICIO VARCHAR(250),
PREGUNTA VARCHAR(MAX),
EVALUADO VARCHAR(250),
TIPO VARCHAR(20)

)
CREATE TABLE PLANTILLAENCUESTADVAL
 (
IDPLANTILLALISTA INT IDENTITY (1,1),
CODPLANTILLAENCUESTA INT,
CAMPO INT,
DESCRIPCION VARCHAR(MAX)

)

CREATE TABLE ENCUESTA
(
CODENCUESTA INT IDENTITY(1,1),
CODPLANTILLAENCUESTA INT,
CAMPO VARCHAR(20),
ORDEN INT ,
SERVICIO VARCHAR(250),
PREGUNTA VARCHAR(MAX),
EVALUADO VARCHAR(250),
TIPO VARCHAR(20),
ALFANUMERICO VARCHAR(250),
MEMO VARCHAR(MAX)
)
CREATE TABLE ENCUESTAD
(
CODENCUESTA INT,
CAMPO VARCHAR(20),
ORDEN INT ,
SERVICIO VARCHAR(250),
PREGUNTA VARCHAR(MAX),
EVALUADO VARCHAR(250),
TIPO VARCHAR(20),
ALFANUMERICO VARCHAR(250),
MEMO VARCHAR(MAX)
)

CREATE TABLE RESULTADOENCUESTA(

ID  INT IDENTITY (1,1),
FECHA DATETIME  NOT NULL,
DOCUMENTO VARCHAR(20) NOT NULL,
NOMBREAFI VARCHAR(MAX),
EDAD VARCHAR(20),
DIRECCION VARCHAR(MAX),
TELEFONO VARCHAR(MAX),
EAPB VARCHAR(MAX),
GRUPOPOB VARCHAR(MAX), 
ENCUESTA VARCHAR(MAX),
SERVICIO VARCHAR(100),
PREGUNTA VARCHAR(MAX), 
EVALUADO VARCHAR(MAX),
VALOR VARCHAR(MAX))