
ALTER PROCEDURE SP_GUARDAR_RESULTADOENCUESTA 
 @DATOS VARCHAR(MAX),
--='rbtJAGRUrgenciaJAGRComo Evalúa la atención Recibida en el Servicio de UrgenciaJAGRMEDICO ESPECIALISTAJAGR1JAGRMala'
 @DOCUMENTO  VARCHAR(20),
--='1118841534'
 @ENCUESTA VARCHAR(MAX)
--='ENCUESTA DE SATISFACION'

--SELECT * FROM string_split(REPLACE(@DATOS,'JAGR',','),',')

AS
BEGIN

CREATE TABLE #A ( ID INT IDENTITY , VALOR VARCHAR(MAX))

INSERT INTO #A (VALOR)
SELECT * FROM string_split(REPLACE(@DATOS,'JAGR',','),',')

INSERT INTO RESULTADOENCUESTA (FECHA,DOCUMENTO,NOMBREAFI,EDAD,DIRECCION,TELEFONO,EAPB,GRUPOPOB,ENCUESTA,SERVICIO,PREGUNTA,EVALUADO,VALOR,DATOS)
SELECT GETDATE()FECHA, AFI.DOCIDAFILIADO DOCUMENTO,AFI.NOMBREAFI ,
AFI.EDAD ,
AFI.DIRECCION ,
AFI.TELEFONORES TELEFONO ,
TER.RAZONSOCIAL EAPB ,
TGEN.DESCRIPCION GRUPOPOB , 
@ENCUESTA,
REPLACE(REPLACE(REPLACE(REPLACE(SERVICIO.VALOR, 'Blanco',''),'1sp4c10',' '),'C0m4',','),'Pr3gunt4','?')SERVICIO,
REPLACE(REPLACE(REPLACE(REPLACE(PREGUNTA.VALOR, 'Blanco',''),'1sp4c10',' '),'C0m4',','),'Pr3gunt4','?') PREGUNTA,
REPLACE(REPLACE(REPLACE(REPLACE(EVALUADO.VALOR,'Blanco',''),'1sp4c10',' '),'C0m4',','),'Pr3gunt4','?') EVALUADO,
VALOR.VALOR VALOR,@DATOS
 FROM AFI  LEFT JOIN TGEN ON TGEN.CODIGO=AFI.GRUPOPOB AND TGEN.CAMPO='GRUPOPOB' AND TGEN.TABLA='General'
		 LEFT JOIN TER ON AFI.IDADMINISTRADORA=TER.IDTERCERO
CROSS JOIN (SELECT * FROM #A WHERE ID=2) SERVICIO
 CROSS JOIN (SELECT * FROM #A WHERE ID=3) PREGUNTA

CROSS JOIN (SELECT * FROM #A WHERE ID=4) EVALUADO
CROSS JOIN (SELECT * FROM #A WHERE ID=6) VALOR

WHERE DOCIDAFILIADO=@DOCUMENTO

DROP TABLE #A

END